# Generated by Django 6.0.3 on 2026-03-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=4.5)),
                ('delivery_time', models.IntegerField(default=30)),
                ('cuisines', models.CharField(help_text='e.g. North Indian, Chinese', max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
