# Generated by Django 6.0.3 on 2026-03-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_menuitem_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_combo_eligible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
